name: GCP Cloud Run Deploy

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker to Google Cloud Registry
      run: |
        echo "${{ secrets.GCP_SERVICE_KEY }}" | base64 --decode > keyfile.json
        gcloud auth activate-service-account --key-file=keyfile.json
        gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flask-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
